baseURL = "https://poslog.pl/"
languageCode = "pl"
title = "poslog v2"
theme = "terminal"

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal"
    
[params]
  themeColor = "yellow"
  showMenu = true
  centerTheme = true
  fullWidthTheme = false
  showLastUpdated = true
  readingTime = true
  contentType = "posts"
  subtitle = "Minimalistyczny log o biznesie, technologiach i myśleniu"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "O mnie"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Logi"
    url = "/posts"
    weight = 2

  [[menu.main]]
    name = "Kontakt"
    url = "/contact"
    weight = 3

