[build]
  publish = "public"
  command = "hugo --gc --minify --cleanDestinationDir"

[context.production.environment]
  HUGO_VERSION = "0.121.1"
  HUGO_ENABLEGITINFO = "true"
  GIT_SUBMODULE_STRATEGY = "recursive"
